-- insert into oauth_client_details
--   (client_id, client_secret, resource_ids, scope, authorized_grant_types, web_server_redirect_uri, authorities,
--   access_token_validity, refresh_token_validity, additional_information, autoapprove)
--   values ('client', 'secret', null, 'read,write', 'authorization_code,password,client_credentials,implicit,refresh_token',
--         null, 'ROLE_USER', 36000, 2592000, null, null);
--
--
--
-- insert into oauth_client_details (client_id, client_secret, resource_ids, scope, authorized_grant_types,
--   web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove)
--   values ('client2', 'secret', null, 'read', 'authorization_code,implicit', null, 'ROLE_ADMIN', 36000, 2592000, null, null);