security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      grant-type: client_credentials
      access-token-uri: http://localhost:8080/oauth/access_token
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&useSSL=false
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver