server:
  port: 8083
  context-path: /api

security:
  oauth2:
    resource:
      jwt:
        keyUri: http://localhost:8081/oauth/token_key

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver