server:
  port: 8083
  context-path: /api

config:
  oauth2:
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA1P1tnrMJEMwia/4mP5hBplsA4+iQxZXpzDkVraPL7aEjJHJD
      OCZqaYZ9QxS/UWNU3GPEEnD4QRKEx9/HKaAs5i6htr6duio1s4OvxJXQyhCU0wGL
      14o8SWz8tfYLhwEnuVLBQvr1rOl/y3X2dj33O/3HCSOiVpY/BR7l7nHcELgyogmB
      YpKuJhgKiR3b7PDGJrpIGHo+gT92PbZaQTfO+bCTfGQDJzjZWVZJQjk/v5HsI68S
      5yKcTVCUJfFWPStBXWIMDLZUK7RN4Tz9JwmfeYHk3+2NheRDSu3xdODhITzgT1Hx
      zbe5k+xVcdVutqdMKYziVHmEdYoikEO8WolPfQIDAQABAoIBAH6SRCyFNKP4y5Pl
      qpEsSAc2GWdW84GXvyKP4eQYbL3AfoPQK0YY/i/LrnDIyZDyOKHn38Mdw0nYWXP1
      9gM0nroDiDJzQIQ7RUJyxWdLqJIMHITwbEwgaAcyb1Mq7lrCQvsMxLCrNogVEs60
      QUyvMldCTp+Nv5E5JCZE4Fs86ow79INQ/J+7/8F9rHwx8355r2QH5Fb7mon9g30F
      OEVutpFeZyESvrvVEBNGWWCi64FCLibrsAYEcX08uQ1iHJl0N40ev+uS7YfHMNdG
      ZH1JJCSNaX6WBDM3f+jAqRU5De73+FqFIdDZTta3OUKl0fC6fjfDrREn8TS7NBsl
      OZ2r94ECgYEA85iBvUkKWdfpRBj/iACMXzy2zcwyBLrvNfV2YItiRivsTWy2AqhJ
      hbjujVvAoJG/U51eRo6gPnN95Lb6IDbauhincxyDxmCqsyd1jIii8lf83wF3vK1i
      EJS3Z9lngrEQBHmO2DFXoQ0blrbWFw7L7H9LRTevMeB+IGxsaIDC5u0CgYEA39Xy
      dnBtG0DbI0q6Ktnp6vVgdbefd+hB1To+jBChQEmjj+h2/EkCd+vttGnau4V/g64t
      NGbIfidYkP+zMQ7k0DIqCF12//3HJS48J8AVqKMKfCWwz8yPe1FWP2xDspnxJvao
      ZcFFG7iWWU6IT5tCg6HHDrSBojtcAwt42jo06NECgYAJEbyC151TCv7cUjHxVlPj
      l9cWgmu6UVtmnuTxYz8dbbU2jL2aC7nxCJmZGblqQQLmkg1YgybkLFibk1Rsrp4m
      H5TcbEtbr22rjeSKfuvSKgR4KQ3UMIBeLatGaom4C++UuxHearfgfyRv0A7YfOyK
      uZKL2S7kpH8NpfvDSEf5YQKBgQDSwTSxtjvVHGT5PuQ5csMgevfe/w0ErshFx7ia
      0xGxYWTDHEPkWa4cUiWX6M+OHy2oQ/jGTTzcI5nttQT43Sguq/0NsUtZz46SAI2d
      c+www4scx7RKhDZZC4Wk5AB+CxqX8EkwviCe8FeIMTyBkBO5szqlKuqgYTnKmCOr
      foDQ8QKBgQDo9khM0MHB8RXZ+szcvI44jb68Qj2HSZYa4K2Bpg7/EZpD6IcCSJWt
      /buvaMtjvgAa9gA/FtSa9QjERHzF0YwtodztMTPbpGfdiJvA2sJ5DabeGkJ5pTrR
      6Trm6gkJRnzQcRIoYA9bxXrz2ahlm/VkgYZO/s2O/VjYhmD/X3il9A==
      -----END RSA PRIVATE KEY-----
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1P1tnrMJEMwia/4mP5hB
      plsA4+iQxZXpzDkVraPL7aEjJHJDOCZqaYZ9QxS/UWNU3GPEEnD4QRKEx9/HKaAs
      5i6htr6duio1s4OvxJXQyhCU0wGL14o8SWz8tfYLhwEnuVLBQvr1rOl/y3X2dj33
      O/3HCSOiVpY/BR7l7nHcELgyogmBYpKuJhgKiR3b7PDGJrpIGHo+gT92PbZaQTfO
      +bCTfGQDJzjZWVZJQjk/v5HsI68S5yKcTVCUJfFWPStBXWIMDLZUK7RN4Tz9Jwmf
      eYHk3+2NheRDSu3xdODhITzgT1Hxzbe5k+xVcdVutqdMKYziVHmEdYoikEO8WolP
      fQIDAQAB
      -----END PUBLIC KEY-----