server:
  port: 8082
  context-path: /client

security:
  basic:
    enabled: false

config:
  oauth2:
    clientId: client
    clientSecret: secret
    accessTokenUri: http://localhost:8081/oauth/token
    userAuthorizationUri: http://localhost:8081/oauth/authorize
    resourceUri: http://localhost:8083/api